server:
  port: 8090

spring:
  cloud:
    config:
      server:
        fail-fast: false
        git:
          uri: https://github.com/OmarSaez/prestabank-microservice
          default-label: main
          search-paths: config-data

  application:
    name: Confing-Server

logging:
  level:
    org.springframework: DEBUG
    org.springframework.boot: DEBUG

