server:
  port: 8090
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/OmarSaez/prestabank-microservice
          search-paths: config-data
  application:
    name: config-service

