server:
  port: 8050
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8092/eureka
  instance:
    prefer-ip-address: true
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: M1-Simulation
          uri: lb://M1-Simulation
          predicates:
            - Path=/api/loan/simulate/**
        - id: M2-Register
          uri: lb://M2-Register
          predicates:
            - Path=/api/user/**
        - id: M3-Request
          uri: lb://M3-Request
          predicates:
            - Path=/api/loan/**