server:
  port: 8050

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: m1_simulation_router
          uri: lb://SIMULATION
          predicates:
            - Path=/api/loan/simulate/**
        - id: m2_register_router
          uri: lb://REGISTER
          predicates:
            - Path=/api/user/**

      httpclient:
        connect-timeout: 5000
        response-timeout: 10000

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

