server:
  port: 8050
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: m1_simulation_router
          uri: http://m1_simulation
          predicates:
            - Path=/api/loan/simulate**
