apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-deployment
  labels:
    app: config-deployment   # Cambié de 'apps' a 'app' para consistencia
spec:
  replicas: 2
  selector:
    matchLabels:
      app: config-deployment  # Coincide con el Service
  template:
    metadata:
      labels:
        app: config-deployment  # Coincide con el selector
    spec:
      containers:
        - name: config-service  # Nombre descriptivo del contenedor
          image: omarsaez/config-service:latest
          ports:
            - containerPort: 8090  # Es el puerto en el que el contenedor escucha dentro del Pod. Esto coincide con el puerto definido en tu código
---
apiVersion: v1
kind: Service
metadata:
  name: config-service  # Un nombre único para el Service
  labels:
    app: config-deployment  # Coincide con el Deployment
spec:
  selector:
    app: config-deployment  # Debe coincidir con las etiquetas del Deployment
  ports:
    - protocol: TCP
      port: 8090            # Es el puerto que expone el Service dentro del clúster Kubernetes. Los demás microservicios usan este puerto para comunicarse.
      targetPort: 8090      # Es el puerto interno del Pod al que el Service enviará las solicitudes. Debe coincidir con el containerPort.
  type: ClusterIP          # Comunicación interna (no expone a fuera del clúster)
