apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
  labels:
    apps: front-deployment
spec:
  selector:
    matchLabels:
      app: front-deployment
  replicas: 2
  template:
    metadata:
      labels:
        app: front-deployment
    spec:
      containers:
      - name: front-deployment
        image: omarsaez/frontend-microsevicio:latest
        ports:
        - containerPort: 5173
---
apiVersion: v1
kind: Service
metadata:
  name: front-service
  labels:
    apps: front-deployment
spec:
  selector:
    app: front-deployment
  ports:
    - protocol: TCP
      port: 80          # Puerto dentro del clúster
      targetPort: 80     # Puerto dentro del contenedor
      nodePort: 30000     # Puerto en el nodo para acceder desde fuera del clúster
      #Para que funcione, el valor de nodePort debe estar entre 30000 y 32767.
  type: NodePort