apiVersion: apps/v1
kind: Deployment
metadata:
  name: m1-simulation
  labels:
    app: m1-simulation
spec:
  selector:
    matchLabels:
      app: m1-simulation
  replicas: 2
  template:
    metadata:
      labels:
        app: m1-simulation
    spec:
      containers:
        - name: m1-simulation
          image: omarsaez/m1-simulation:latest
          ports:
            - containerPort: 8061  # Puerto fijo del contenedor (debe coincidir con el configurado por defecto en tu aplicación)
          env:
            - name: SERVER_PORT
              value: "0"  # Puerto aleatorio
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-m1  # ConfigMap para el host y el nombre de la base de datos
                  key: host
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-m1  # ConfigMap para el nombre de la base de datos
                  key: name
            - name: DB_USERNAME
              value: root  # Usuario root directamente
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-root-credentials  # El secret que contiene la contraseña root
                  key: password
