apiVersion: apps/v1
kind: Deployment
metadata:
  name: m2-register
  labels:
    app: m2-register
spec:
  selector:
    matchLabels:
      app: m2-register
  replicas: 2
  template:
    metadata:
      labels:
        app: m2-register
    spec:
      containers:
        - name: m2-register
          image: omarsaez/m2-register:latest
          ports:
            - containerPort: 8002
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-m2  # ConfigMap para el host y el nombre de la base de datos
                  key: host
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-m2  # ConfigMap para el nombre de la base de datos
                  key: name
            - name: DB_USERNAME
              value: root  # Usuario root directamente
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-root-credentials  # El secret que contiene la contraseña root
                  key: password
