server:
  port: 8090

spring:
  cloud:
    config:
      server:
        fail-fast: false
        git:
          uri: https://github.com/OmarSaez/prestabank-microservice
          default-label: main
          search-paths: config-data

  application:
    name: config-service